# Deep Learning Blitz

In [45]:
import torch
import numpy as np

## Tensors

In [13]:
# Constructing a 5 x 3 matrix of zeros

x = torch.empty(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
# Constructing a 5 x 3 matrix with random values

x = torch.rand(5, 3)
x

tensor([[0.2327, 0.4142, 0.5414],
        [0.7240, 0.2366, 0.9097],
        [0.0234, 0.5596, 0.0239],
        [0.4584, 0.9063, 0.7659],
        [0.7907, 0.8400, 0.4473]])

In [17]:
# Constructing a 5 x 3 matrix filled with zeros of dtype long

x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [18]:
# Constructing a tensor directly from data

x = torch.tensor([3.14, 6.18])
x

tensor([3.1400, 6.1800])

In [20]:
# Create a new tensore based on another

x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0146, -0.5414,  0.2056],
        [-0.2903,  0.7867, -1.3890],
        [-0.4571,  0.4369, -0.2362],
        [-1.0425, -2.3861, -0.8568],
        [-0.3110, -1.4198,  1.1166]])


In [21]:
# Get the shape of a tensor

x.size()

torch.Size([5, 3])

## Tensor Operations

In [24]:
x = torch.rand(3, 3)
y = torch.rand(3, 3)

z = x + y
z_2 = torch.add(x, y)

print(x)
print(y)
print(z)
print(z_2)

tensor([[0.7092, 0.4650, 0.2682],
        [0.4332, 0.1213, 0.6822],
        [0.7261, 0.1203, 0.2334]])
tensor([[0.3057, 0.7194, 0.7626],
        [0.5535, 0.2738, 0.9569],
        [0.6140, 0.1797, 0.3105]])
tensor([[1.0149, 1.1844, 1.0309],
        [0.9868, 0.3951, 1.6391],
        [1.3401, 0.3000, 0.5439]])
tensor([[1.0149, 1.1844, 1.0309],
        [0.9868, 0.3951, 1.6391],
        [1.3401, 0.3000, 0.5439]])


In [26]:
# In-place addition. Any operation that does in-place operations has '_' post fixed.

y.add_(x)
y

tensor([[1.7241, 1.6494, 1.2991],
        [1.4200, 0.5164, 2.3213],
        [2.0662, 0.4203, 0.7773]])

In [29]:
x = torch.randn(3, 3)
x

tensor([[ 0.7593, -0.5042, -1.1148],
        [-0.7923, -1.0351,  0.6849],
        [ 0.0739,  0.7183,  0.1048]])

In [32]:
# Access rows

r1 = x[0]
r2 = x[1]
r3 = x[2]

r1, r2, r3

(tensor([ 0.7593, -0.5042, -1.1148]),
 tensor([-0.7923, -1.0351,  0.6849]),
 tensor([0.0739, 0.7183, 0.1048]))

In [35]:
# Access columns

c1 = x[:, 0]
c2 = x[:, 1]
c3 = x[:, 2]

c1, c2, c3

(tensor([ 0.7593, -0.7923,  0.0739]),
 tensor([-0.5042, -1.0351,  0.7183]),
 tensor([-1.1148,  0.6849,  0.1048]))

In [41]:
# Resizing tensors

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # size -1 is inferred from other dimensions

x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

## Torch Tensor to Numpy and Back

In [42]:
x = torch.ones(5)
x

tensor([1., 1., 1., 1., 1.])

In [44]:
y = x.numpy()
y

array([1., 1., 1., 1., 1.], dtype=float32)

In [46]:
z = torch.from_numpy(y)
z

tensor([1., 1., 1., 1., 1.])

## CUDA Tensors

In [47]:
torch.cuda.is_available()

False

In [49]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.randn(3, 3, device=device)  # Initialize tensore on GPU
    y = torch.randn(4, 4)                 # Send densore to GPU
    y = y.to(device)
    print(x)
    print(y)

# Autograd: Automatic Differentiation

In [51]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [53]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [54]:
y.grad_fn

In [55]:
z = y * y * 3
out = z.mean()

z, out

(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [56]:
# Backprop

out.backward()

# print gradients d(out) / dx
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])